
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Image ketv7;

	private global::Gtk.Image ketv6;

	private global::Gtk.Image ketv5;

	private global::Gtk.Image ketv4;

	private global::Gtk.Image ketv3;

	private global::Gtk.Image ketv2;

	private global::Gtk.Image ketv1;

	private global::Gtk.Image ketvirtouzv3;

	private global::Gtk.Image ketvirtoatv3;

	private global::Gtk.Image ketvirtouzv2;

	private global::Gtk.Image ketvirtoatv2;

	private global::Gtk.Image ketvirtouzv1;

	private global::Gtk.Image ketvirtoatv1;

	private global::Gtk.Image trec1;

	private global::Gtk.Image trec2;

	private global::Gtk.Image trec3;

	private global::Gtk.Image trec4;

	private global::Gtk.Image trec5;

	private global::Gtk.Image trec6;

	private global::Gtk.Image treciouzv3;

	private global::Gtk.Image trecioatv3;

	private global::Gtk.Image treciouzv2;

	private global::Gtk.Image trecioatv2;

	private global::Gtk.Image treciouzv1;

	private global::Gtk.Image trecioatv1;

	private global::Gtk.Image pirmouzv1;

	private global::Gtk.Image pirmouzv2;

	private global::Gtk.Image pirmouzv3;

	private global::Gtk.Image pirmoatv1;

	private global::Gtk.Image pirmoatv2;

	private global::Gtk.Image pirmoatv3;

	private global::Gtk.Image antrouzv3;

	private global::Gtk.Image antrouzv2;

	private global::Gtk.Image antrouzv1;

	private global::Gtk.Image antroatv3;

	private global::Gtk.Image antr6;

	private global::Gtk.Image antr5;

	private global::Gtk.Image antr4;

	private global::Gtk.Image antr3;

	private global::Gtk.Image antr2;

	private global::Gtk.Image antr1;

	private global::Gtk.Image antr12;

	private global::Gtk.Image antr11;

	private global::Gtk.Image antr10;

	private global::Gtk.Image antr9;

	private global::Gtk.Image antr8;

	private global::Gtk.Image antr7;

	private global::Gtk.Image antr15;

	private global::Gtk.Image antr13;

	private global::Gtk.Image antr14;

	private global::Gtk.Button button2;

	private global::Gtk.Image GUIkalade;

	private global::Gtk.Image pir1;

	private global::Gtk.Image pir2;

	private global::Gtk.Image pir3;

	private global::Gtk.Image pir4;

	private global::Gtk.Image pir5;

	private global::Gtk.Image pir6;

	private global::Gtk.Image pir7;

	private global::Gtk.Image pir8;

	private global::Gtk.Image pir9;

	private global::Gtk.Image pir10;

	private global::Gtk.Image pir11;

	private global::Gtk.Image pir12;

	private global::Gtk.Image pir13;

	private global::Gtk.Image pir14;

	private global::Gtk.Image pir15;

	private global::Gtk.Image pir16;

	private global::Gtk.Image zaidziamos;

	private global::Gtk.Image trec7;

	private global::Gtk.Label label1;

	private global::Gtk.Image antroatv2;

	private global::Gtk.Image antroatv1;

	private global::Gtk.Image ketv8;

	private global::Gtk.Image ketv9;

	private global::Gtk.Image ketv10;

	private global::Gtk.Image ketv11;

	private global::Gtk.Image ketv12;

	private global::Gtk.Image ketv13;

	private global::Gtk.Image ketv14;

	private global::Gtk.Image ketv15;

	private global::Gtk.Image trec8;

	private global::Gtk.Image trec9;

	private global::Gtk.Image trec10;

	private global::Gtk.Image trec11;

	private global::Gtk.Image trec12;

	private global::Gtk.Image trec13;

	private global::Gtk.Image trec14;

	private global::Gtk.Image trec15;

	private global::Gtk.Button Imti_viska;

	private global::Gtk.Button imti_3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv7 = new global::Gtk.Image();
		this.ketv7.Name = "ketv7";
		this.fixed1.Add(this.ketv7);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv7]));
		w1.X = 30;
		w1.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv6 = new global::Gtk.Image();
		this.ketv6.Name = "ketv6";
		this.fixed1.Add(this.ketv6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv6]));
		w2.X = 30;
		w2.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv5 = new global::Gtk.Image();
		this.ketv5.Name = "ketv5";
		this.fixed1.Add(this.ketv5);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv5]));
		w3.X = 30;
		w3.Y = 375;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv4 = new global::Gtk.Image();
		this.ketv4.Name = "ketv4";
		this.fixed1.Add(this.ketv4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv4]));
		w4.X = 30;
		w4.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv3 = new global::Gtk.Image();
		this.ketv3.Name = "ketv3";
		this.fixed1.Add(this.ketv3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv3]));
		w5.X = 30;
		w5.Y = 430;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv2 = new global::Gtk.Image();
		this.ketv2.Name = "ketv2";
		this.fixed1.Add(this.ketv2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv2]));
		w6.X = 30;
		w6.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv1 = new global::Gtk.Image();
		this.ketv1.Name = "ketv1";
		this.fixed1.Add(this.ketv1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv1]));
		w7.X = 30;
		w7.Y = 480;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtouzv3 = new global::Gtk.Image();
		this.ketvirtouzv3.Name = "ketvirtouzv3";
		this.fixed1.Add(this.ketvirtouzv3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtouzv3]));
		w8.X = 170;
		w8.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtoatv3 = new global::Gtk.Image();
		this.ketvirtoatv3.Name = "ketvirtoatv3";
		this.fixed1.Add(this.ketvirtoatv3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtoatv3]));
		w9.X = 140;
		w9.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtouzv2 = new global::Gtk.Image();
		this.ketvirtouzv2.Name = "ketvirtouzv2";
		this.fixed1.Add(this.ketvirtouzv2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtouzv2]));
		w10.X = 170;
		w10.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtoatv2 = new global::Gtk.Image();
		this.ketvirtoatv2.Name = "ketvirtoatv2";
		this.fixed1.Add(this.ketvirtoatv2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtoatv2]));
		w11.X = 140;
		w11.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtouzv1 = new global::Gtk.Image();
		this.ketvirtouzv1.Name = "ketvirtouzv1";
		this.fixed1.Add(this.ketvirtouzv1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtouzv1]));
		w12.X = 170;
		w12.Y = 450;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketvirtoatv1 = new global::Gtk.Image();
		this.ketvirtoatv1.Name = "ketvirtoatv1";
		this.fixed1.Add(this.ketvirtoatv1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketvirtoatv1]));
		w13.X = 140;
		w13.Y = 450;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec1 = new global::Gtk.Image();
		this.trec1.Name = "trec1";
		this.fixed1.Add(this.trec1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec1]));
		w14.X = 300;
		w14.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec2 = new global::Gtk.Image();
		this.trec2.Name = "trec2";
		this.fixed1.Add(this.trec2);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec2]));
		w15.X = 350;
		w15.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec3 = new global::Gtk.Image();
		this.trec3.Name = "trec3";
		this.fixed1.Add(this.trec3);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec3]));
		w16.X = 400;
		w16.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec4 = new global::Gtk.Image();
		this.trec4.Name = "trec4";
		this.fixed1.Add(this.trec4);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec4]));
		w17.X = 450;
		w17.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec5 = new global::Gtk.Image();
		this.trec5.Name = "trec5";
		this.fixed1.Add(this.trec5);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec5]));
		w18.X = 500;
		w18.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec6 = new global::Gtk.Image();
		this.trec6.Name = "trec6";
		this.fixed1.Add(this.trec6);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec6]));
		w19.X = 550;
		w19.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.treciouzv3 = new global::Gtk.Image();
		this.treciouzv3.Name = "treciouzv3";
		this.fixed1.Add(this.treciouzv3);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.treciouzv3]));
		w20.X = 350;
		w20.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trecioatv3 = new global::Gtk.Image();
		this.trecioatv3.Name = "trecioatv3";
		this.fixed1.Add(this.trecioatv3);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trecioatv3]));
		w21.X = 350;
		w21.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.treciouzv2 = new global::Gtk.Image();
		this.treciouzv2.Name = "treciouzv2";
		this.fixed1.Add(this.treciouzv2);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.treciouzv2]));
		w22.X = 435;
		w22.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trecioatv2 = new global::Gtk.Image();
		this.trecioatv2.Name = "trecioatv2";
		this.fixed1.Add(this.trecioatv2);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trecioatv2]));
		w23.X = 435;
		w23.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.treciouzv1 = new global::Gtk.Image();
		this.treciouzv1.Name = "treciouzv1";
		this.fixed1.Add(this.treciouzv1);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.treciouzv1]));
		w24.X = 520;
		w24.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trecioatv1 = new global::Gtk.Image();
		this.trecioatv1.Name = "trecioatv1";
		this.fixed1.Add(this.trecioatv1);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trecioatv1]));
		w25.X = 520;
		w25.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmouzv1 = new global::Gtk.Image();
		this.pirmouzv1.Name = "pirmouzv1";
		this.fixed1.Add(this.pirmouzv1);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmouzv1]));
		w26.X = 350;
		w26.Y = 580;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmouzv2 = new global::Gtk.Image();
		this.pirmouzv2.Name = "pirmouzv2";
		this.fixed1.Add(this.pirmouzv2);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmouzv2]));
		w27.X = 435;
		w27.Y = 580;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmouzv3 = new global::Gtk.Image();
		this.pirmouzv3.Name = "pirmouzv3";
		this.fixed1.Add(this.pirmouzv3);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmouzv3]));
		w28.X = 520;
		w28.Y = 580;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmoatv1 = new global::Gtk.Image();
		this.pirmoatv1.Name = "pirmoatv1";
		this.fixed1.Add(this.pirmoatv1);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmoatv1]));
		w29.X = 350;
		w29.Y = 610;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmoatv2 = new global::Gtk.Image();
		this.pirmoatv2.Name = "pirmoatv2";
		this.fixed1.Add(this.pirmoatv2);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmoatv2]));
		w30.X = 435;
		w30.Y = 610;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pirmoatv3 = new global::Gtk.Image();
		this.pirmoatv3.Name = "pirmoatv3";
		this.fixed1.Add(this.pirmoatv3);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pirmoatv3]));
		w31.X = 520;
		w31.Y = 610;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antrouzv3 = new global::Gtk.Image();
		this.antrouzv3.Name = "antrouzv3";
		this.fixed1.Add(this.antrouzv3);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antrouzv3]));
		w32.X = 700;
		w32.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antrouzv2 = new global::Gtk.Image();
		this.antrouzv2.Name = "antrouzv2";
		this.fixed1.Add(this.antrouzv2);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antrouzv2]));
		w33.X = 700;
		w33.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antrouzv1 = new global::Gtk.Image();
		this.antrouzv1.Name = "antrouzv1";
		this.fixed1.Add(this.antrouzv1);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antrouzv1]));
		w34.X = 700;
		w34.Y = 450;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antroatv3 = new global::Gtk.Image();
		this.antroatv3.Name = "antroatv3";
		this.fixed1.Add(this.antroatv3);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antroatv3]));
		w35.X = 730;
		w35.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr6 = new global::Gtk.Image();
		this.antr6.Name = "antr6";
		this.fixed1.Add(this.antr6);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr6]));
		w36.X = 840;
		w36.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr5 = new global::Gtk.Image();
		this.antr5.Name = "antr5";
		this.fixed1.Add(this.antr5);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr5]));
		w37.X = 840;
		w37.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr4 = new global::Gtk.Image();
		this.antr4.Name = "antr4";
		this.fixed1.Add(this.antr4);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr4]));
		w38.X = 840;
		w38.Y = 375;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr3 = new global::Gtk.Image();
		this.antr3.Name = "antr3";
		this.fixed1.Add(this.antr3);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr3]));
		w39.X = 840;
		w39.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr2 = new global::Gtk.Image();
		this.antr2.Name = "antr2";
		this.fixed1.Add(this.antr2);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr2]));
		w40.X = 840;
		w40.Y = 430;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr1 = new global::Gtk.Image();
		this.antr1.Name = "antr1";
		this.fixed1.Add(this.antr1);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr1]));
		w41.X = 840;
		w41.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr12 = new global::Gtk.Image();
		this.antr12.Name = "antr12";
		this.fixed1.Add(this.antr12);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr12]));
		w42.X = 870;
		w42.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr11 = new global::Gtk.Image();
		this.antr11.Name = "antr11";
		this.fixed1.Add(this.antr11);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr11]));
		w43.X = 870;
		w43.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr10 = new global::Gtk.Image();
		this.antr10.Name = "antr10";
		this.fixed1.Add(this.antr10);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr10]));
		w44.X = 870;
		w44.Y = 375;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr9 = new global::Gtk.Image();
		this.antr9.Name = "antr9";
		this.fixed1.Add(this.antr9);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr9]));
		w45.X = 870;
		w45.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr8 = new global::Gtk.Image();
		this.antr8.Name = "antr8";
		this.fixed1.Add(this.antr8);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr8]));
		w46.X = 870;
		w46.Y = 430;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr7 = new global::Gtk.Image();
		this.antr7.Name = "antr7";
		this.fixed1.Add(this.antr7);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr7]));
		w47.X = 870;
		w47.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr15 = new global::Gtk.Image();
		this.antr15.Name = "antr15";
		this.fixed1.Add(this.antr15);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr15]));
		w48.X = 900;
		w48.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr13 = new global::Gtk.Image();
		this.antr13.Name = "antr13";
		this.fixed1.Add(this.antr13);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr13]));
		w49.X = 900;
		w49.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antr14 = new global::Gtk.Image();
		this.antr14.Name = "antr14";
		this.fixed1.Add(this.antr14);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antr14]));
		w50.X = 900;
		w50.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Pradeti");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w51.X = 432;
		w51.Y = 420;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GUIkalade = new global::Gtk.Image();
		this.GUIkalade.Name = "GUIkalade";
		this.fixed1.Add(this.GUIkalade);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GUIkalade]));
		w52.X = 520;
		w52.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir1 = new global::Gtk.Image();
		this.pir1.Name = "pir1";
		this.fixed1.Add(this.pir1);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir1]));
		w53.X = 300;
		w53.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir2 = new global::Gtk.Image();
		this.pir2.Name = "pir2";
		this.fixed1.Add(this.pir2);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir2]));
		w54.X = 350;
		w54.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir3 = new global::Gtk.Image();
		this.pir3.Name = "pir3";
		this.fixed1.Add(this.pir3);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir3]));
		w55.X = 400;
		w55.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir4 = new global::Gtk.Image();
		this.pir4.Name = "pir4";
		this.fixed1.Add(this.pir4);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir4]));
		w56.X = 450;
		w56.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir5 = new global::Gtk.Image();
		this.pir5.Name = "pir5";
		this.fixed1.Add(this.pir5);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir5]));
		w57.X = 500;
		w57.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir6 = new global::Gtk.Image();
		this.pir6.Name = "pir6";
		this.fixed1.Add(this.pir6);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir6]));
		w58.X = 550;
		w58.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir7 = new global::Gtk.Image();
		this.pir7.Name = "pir7";
		this.fixed1.Add(this.pir7);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir7]));
		w59.X = 600;
		w59.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir8 = new global::Gtk.Image();
		this.pir8.Name = "pir8";
		this.fixed1.Add(this.pir8);
		global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir8]));
		w60.X = 650;
		w60.Y = 720;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir9 = new global::Gtk.Image();
		this.pir9.Name = "pir9";
		this.fixed1.Add(this.pir9);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir9]));
		w61.X = 300;
		w61.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir10 = new global::Gtk.Image();
		this.pir10.Name = "pir10";
		this.fixed1.Add(this.pir10);
		global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir10]));
		w62.X = 350;
		w62.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir11 = new global::Gtk.Image();
		this.pir11.Name = "pir11";
		this.fixed1.Add(this.pir11);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir11]));
		w63.X = 400;
		w63.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir12 = new global::Gtk.Image();
		this.pir12.Name = "pir12";
		this.fixed1.Add(this.pir12);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir12]));
		w64.X = 450;
		w64.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir13 = new global::Gtk.Image();
		this.pir13.Name = "pir13";
		this.fixed1.Add(this.pir13);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir13]));
		w65.X = 500;
		w65.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir14 = new global::Gtk.Image();
		this.pir14.Name = "pir14";
		this.fixed1.Add(this.pir14);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir14]));
		w66.X = 550;
		w66.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir15 = new global::Gtk.Image();
		this.pir15.Name = "pir15";
		this.fixed1.Add(this.pir15);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir15]));
		w67.X = 600;
		w67.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pir16 = new global::Gtk.Image();
		this.pir16.Name = "pir16";
		this.fixed1.Add(this.pir16);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pir16]));
		w68.X = 650;
		w68.Y = 800;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.zaidziamos = new global::Gtk.Image();
		this.zaidziamos.Name = "zaidziamos";
		this.fixed1.Add(this.zaidziamos);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.zaidziamos]));
		w69.X = 435;
		w69.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec7 = new global::Gtk.Image();
		this.trec7.Name = "trec7";
		this.fixed1.Add(this.trec7);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec7]));
		w70.X = 600;
		w70.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Valdymas: vaiksciojimas per kortas rodykles i sonus, padet korta rodykle i virsu," +
				" paimt uzversta i apacia");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w71.X = 179;
		w71.Y = 51;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antroatv2 = new global::Gtk.Image();
		this.antroatv2.Name = "antroatv2";
		this.fixed1.Add(this.antroatv2);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antroatv2]));
		w72.X = 730;
		w72.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.antroatv1 = new global::Gtk.Image();
		this.antroatv1.Name = "antroatv1";
		this.fixed1.Add(this.antroatv1);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.antroatv1]));
		w73.X = 730;
		w73.Y = 450;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv8 = new global::Gtk.Image();
		this.ketv8.Name = "ketv8";
		this.fixed1.Add(this.ketv8);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv8]));
		w74.X = -14;
		w74.Y = 502;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv9 = new global::Gtk.Image();
		this.ketv9.Name = "ketv9";
		this.fixed1.Add(this.ketv9);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv9]));
		w75.X = -8;
		w75.Y = 505;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv10 = new global::Gtk.Image();
		this.ketv10.Name = "ketv10";
		this.fixed1.Add(this.ketv10);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv10]));
		w76.X = 10;
		w76.Y = 538;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv11 = new global::Gtk.Image();
		this.ketv11.Name = "ketv11";
		this.fixed1.Add(this.ketv11);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv11]));
		w77.X = 6;
		w77.Y = 537;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv12 = new global::Gtk.Image();
		this.ketv12.Name = "ketv12";
		this.fixed1.Add(this.ketv12);
		global::Gtk.Fixed.FixedChild w78 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv12]));
		w78.X = 7;
		w78.Y = 541;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv13 = new global::Gtk.Image();
		this.ketv13.Name = "ketv13";
		this.fixed1.Add(this.ketv13);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv13]));
		w79.X = 5;
		w79.Y = 548;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv14 = new global::Gtk.Image();
		this.ketv14.Name = "ketv14";
		this.fixed1.Add(this.ketv14);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv14]));
		w80.X = 10;
		w80.Y = 547;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ketv15 = new global::Gtk.Image();
		this.ketv15.Name = "ketv15";
		this.fixed1.Add(this.ketv15);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ketv15]));
		w81.X = 7;
		w81.Y = 535;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec8 = new global::Gtk.Image();
		this.trec8.Name = "trec8";
		this.fixed1.Add(this.trec8);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec8]));
		w82.X = 107;
		w82.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec9 = new global::Gtk.Image();
		this.trec9.Name = "trec9";
		this.fixed1.Add(this.trec9);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec9]));
		w83.X = 107;
		w83.Y = 38;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec10 = new global::Gtk.Image();
		this.trec10.Name = "trec10";
		this.fixed1.Add(this.trec10);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec10]));
		w84.X = 106;
		w84.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec11 = new global::Gtk.Image();
		this.trec11.Name = "trec11";
		this.fixed1.Add(this.trec11);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec11]));
		w85.X = 104;
		w85.Y = 46;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec12 = new global::Gtk.Image();
		this.trec12.Name = "trec12";
		this.fixed1.Add(this.trec12);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec12]));
		w86.X = 97;
		w86.Y = 54;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec13 = new global::Gtk.Image();
		this.trec13.Name = "trec13";
		this.fixed1.Add(this.trec13);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec13]));
		w87.X = 96;
		w87.Y = 65;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec14 = new global::Gtk.Image();
		this.trec14.Name = "trec14";
		this.fixed1.Add(this.trec14);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec14]));
		w88.X = 102;
		w88.Y = 54;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.trec15 = new global::Gtk.Image();
		this.trec15.Name = "trec15";
		this.fixed1.Add(this.trec15);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.trec15]));
		w89.X = 95;
		w89.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Imti_viska = new global::Gtk.Button();
		this.Imti_viska.CanFocus = true;
		this.Imti_viska.Name = "Imti_viska";
		this.Imti_viska.UseUnderline = true;
		this.Imti_viska.Label = global::Mono.Unix.Catalog.GetString("Imti viska");
		this.fixed1.Add(this.Imti_viska);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Imti_viska]));
		w90.X = 717;
		w90.Y = 556;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.imti_3 = new global::Gtk.Button();
		this.imti_3.CanFocus = true;
		this.imti_3.Name = "imti_3";
		this.imti_3.UseUnderline = true;
		this.imti_3.Label = global::Mono.Unix.Catalog.GetString("Imti 3");
		this.fixed1.Add(this.imti_3);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.imti_3]));
		w91.X = 719;
		w91.Y = 601;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1015;
		this.DefaultHeight = 912;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.Imti_viska.Clicked += new global::System.EventHandler(this.OnImtiViskaClicked);
		this.imti_3.Clicked += new global::System.EventHandler(this.OnImti3Clicked);
	}
}
